### ISSUE TITLE
Bug with new server interface (?)

### ISSUE THREAD

**Issue by chrismile** [cgtuebingen/emca#1]
When loading one of the scenes from http://mitsuba-renderer.org/download.html (that has been converted to version 0.6.0 of Mitsuba) in the mitsuba-emca server interface, I get the following warnings/errors on the EMCA client:

```
2021-11-08 13:47:05,271 - root - INFO - [contribution_data] - no final estimate set on server
[...]
Traceback (most recent call last):
  File "/home/christoph/miniconda3/envs/emca/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 270, in process
    func(*args, **kwargs)
  File "/home/christoph/miniconda3/envs/emca/lib/python3.7/site-packages/matplotlib/widgets.py", line 1841, in release
    self._release(event)
  File "/home/christoph/miniconda3/envs/emca/lib/python3.7/site-packages/matplotlib/widgets.py", line 2396, in _release
    self.onselect(self.eventpress, self.eventrelease)
  File "/home/christoph/Programming/Test/emca/core/plot_rgb.py", line 113, in select_r
    self.highlighter.callback_send_update_path(np.int32(self.r_line.get_offsets()[mask,0]), self.highlighter._hold_shift)
  File "/home/christoph/Programming/Test/emca/view/view_sample_contribution/view_sample_contribution_plot.py", line 113, in send_update_path
    self._controller.update_path(indices, add_index)
  File "/home/christoph/Programming/Test/emca/controller/controller.py", line 230, in update_path
    self._view.view_pixel_data.show_path_data(new_indices, self._model.pixel_data)
  File "/home/christoph/Programming/Test/emca/view/view_pixel_data/view_pixel_data.py", line 142, in show_path_data
    self.add_path_data_node(pixel_data.dict_paths[i])
  File "/home/christoph/Programming/Test/emca/view/view_pixel_data/view_pixel_data.py", line 248, in add_path_data_node
    self.add_path_info_node(path, path_data)
  File "/home/christoph/Programming/Test/emca/view/view_pixel_data/view_pixel_data.py", line 265, in add_path_info_node
    [r, g, b] = path_data.final_estimate.to_list_srgb()
AttributeError: 'NoneType' object has no attribute 'to_list_srgb'
```

Due to these problems it seems like I can only view the rendered image, but not any path space statistics.

Here is the output of the client and server (mitsuba-emca):
- [server.txt](https://github.com/cgtuebingen/emca/files/7497028/server.txt)
- [client.txt](https://github.com/cgtuebingen/emca/files/7497029/client.txt)

Is it possible that this is a bug introduced by the recent commits refactoring the server interface or did I maybe do something wrong when compiling/running EMCA? Both versions of the repositories I used contain the latest commits.

**Comment by LukasRuppert** [comment]
Hi,

you need to change the integrator from "[path](https://github.com/cgtuebingen/mitsuba-emca/blob/public/src/integrators/path/path.cpp)" to "[pathemca](https://github.com/cgtuebingen/mitsuba-emca/blob/public/src/integrators/path/pathemca.cpp)" in the scene's XML file to get path data.
I.e., `<integrator type="pathemca"/>`

The default "path" integrator is unchanged and will not collect any data that could be inspected by EMCA.
If you look at the differences between path.cpp and pathemca.cpp, you should also get a good impression of how to customize that data.

And its probably also best to update to the latest version and rebuild first the server module and then Mitsuba.
I made some small changes when writing the interface to Nori 2 for our rendering lecture.

Sorry for the late reply - I did not get any notification about your issue for some reason...

**Comment by chrismile** [comment]
Thanks a lot for your answer! With "pathemca" it's now working.

I understand that this is probably pretty clear to anyone who is already familiar with Mitsuba, but maybe it might still be a good idea to add that to the README.md file of mitsuba-emca as an example of how to use the pre-existing adapted path tracer with Mitsuba scene files. I see that the following text is currently written in README.md of mitsuba-emca:

> All you need to do to add support for EMCA to your path tracer is to add some instrumentation code as explained in the following section. [...] As an example, there is a copy of the default path tracer src/integrators/path/path.cpp at src/integrators/path/pathemca.cpp with added instrumentation for collecting the data needed by the EMCA client. When using EMCA, make sure that your integrator is instrumented accordingly. Otherwise, you will not have access to any path data when using the client.

As someone who is neither familiar with EMCA nor with Mitsuba and just used the mitsuba-emca backend to see what EMCA is capable of to get a first impression of the software, I had difficulties understanding what this description means for me if I just want to use some example renderer without writing own C++ code.

**Comment by LukasRuppert** [comment]
Thanks for your feedback, I've added some text to the readme to make this more clear.
I'm sure there are still quite a few other places that may need more documentation.
Let me know if anything else needs to be added.
I'll close this issue for now.
